server:
  port: 8906

spring:
  application:
    name: auth-srv
  redis:
    database: 1
    host: localhost
    port: 6379
    password: null
    jedis:
      pool:
        max-active: 4
        max-idle: 4
        min-idle: 0
    timeout: 100ms

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8900/eureka/
