server:
  port: 9900

# eureka config
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# spring config
spring:
  application:
    name: gateway-srv
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: order-srv1
          uri: http://localhost:8903/hello
          predicates:
            - Path=/order/hello
          filters:
            - My=false
    loadbalancer:
      ribbon:
        enabled: false
ribbon:
  eureka:
    enabled: false
